#!/bin/bash

# Copyright 2014 Mike Tsao <mike@sowbug.com>

# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

. ./VERSION

pushd nacl_module && \
    make -f TestMakefile clean && \
    make -f TestMakefile && \
    popd

if [ -n "$( git status --porcelain )" ]; then
  echo "Tree is dirty"
  exit 1
else
  # HEAD is what we want to tag.
  TAG="H9_${MAJOR}_${MINOR}_${BUILD}_${PATCH}"
  git tag -a $TAG -m $TAG

  # Now update HEAD to refer to the next version. The reason we leave
  # HEAD on a future version is that we don't want stray builds to be
  # confused with tagged/released builds.
  BUILD_NEXT=`expr $BUILD + 1`
  echo -e "MAJOR=$MAJOR\nMINOR=$MINOR\nBUILD=$BUILD_NEXT\nPATCH=$PATCH" \
      > ./VERSION
  VER_STR="$MAJOR.$MINOR.$BUILD_NEXT.$PATCH"
  git commit -m "Bump version => $VER_STR" VERSION

  # Now build what the tag tagged.
  git checkout $TAG
  make clean
  PRODUCTNAME="Happynine" \
		MAJOR=${MAJOR} BUILD=${BUILD} PATCH=${PATCH} make

  # And put us back on HEAD for further development.
  git checkout master
fi
